### ISSUE TITLE
Migrate all tags from datafusions-orc

### ISSUE THREAD

**Issue by Xuanwo** [datafusion-contrib/orc-rust#7]
I'm not sure if that's possible, but I think it's better to mirror all tags to this repository as well.

**Comment by waynexia** [comment]
Is this the repo that will be moved to Apache ORC?

**Comment by Xuanwo** [comment]
> Is this the repo that will be moved to Apache ORC?

Yep, I believe so. We will transfer this repo to `apache/orc-rust` directly.

**Comment by waynexia** [comment]
Done 😆 (despite the tag's color is changed
